
package monopoly;

import java.util.Random;
import javax.swing.ImageIcon;

/**
 *
 * @author hesha
 */
public class JWindow extends javax.swing.JFrame {

    /**
     * Creates new form BoardWindow
     */
    
    
    
    public JWindow() {
        initComponents();
        //jLabel2.setBounds(Constants.CarStartX, Constants.CarStartY, Constants.CarDim, Constants.CarDim);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BoardPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextField3 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Monopoly");
        setPreferredSize(new java.awt.Dimension(1280, 760));
        setSize(new java.awt.Dimension(1280, 760));

        BoardPanel.setMaximumSize(new java.awt.Dimension(1280, 720));
        BoardPanel.setMinimumSize(new java.awt.Dimension(1280, 720));
        BoardPanel.setName(""); // NOI18N
        BoardPanel.setPreferredSize(new java.awt.Dimension(1280, 720));
        BoardPanel.setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/drawables/CarLeft.png"))); // NOI18N
        BoardPanel.add(jLabel2);
        jLabel2.setBounds(640, 600, 45, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/drawables/board.jpg"))); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(1280, 720));
        jLabel1.setMinimumSize(new java.awt.Dimension(720, 720));
        jLabel1.setPreferredSize(new java.awt.Dimension(720, 720));
        BoardPanel.add(jLabel1);
        jLabel1.setBounds(0, 0, 720, 720);

        jButton1.setText("Roll Dices");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        BoardPanel.add(jButton1);
        jButton1.setBounds(823, 310, 130, 29);

        jTextField3.setText("jTextField3");
        BoardPanel.add(jTextField3);
        jTextField3.setBounds(810, 90, 80, 26);

        jLabel3.setText("just for debugging");
        BoardPanel.add(jLabel3);
        jLabel3.setBounds(804, 70, 90, 16);

        jLabel4.setBounds(new java.awt.Rectangle(920, 150, 110, 110));
        BoardPanel.add(jLabel4);
        jLabel4.setBounds(920, 150, 110, 100);
        BoardPanel.add(jLabel5);
        jLabel5.setBounds(760, 150, 110, 100);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BoardPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BoardPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 738, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    
    Random r1 = new Random();
    int d1 = r1.nextInt(6) + 1;
    ImageIcon icon = loadImageOfDice(d1);
    jLabel4.setIcon(icon);
    
    Random r2 = new Random();
    int d2 = r2.nextInt(6) + 1;
    icon= loadImageOfDice(d2);
    jLabel5.setIcon(icon);
    
    int res = d1 + d2;
    MoveCar(res);
    
    
    
    }//GEN-LAST:event_jButton1ActionPerformed

    
       /* 
       the idea of move function is that
       CurPos Counter starts with zero end with 40 (from go to go)
       every time the car move a city the counter++
       first ten steps move left >=0 & <10
       second ten steps move up >= 10 & <20
       third move steps move left 
       fourth move step move down
        
    move is a for loop starts from 1 until the sum of dice
    each iteration moves 1 step using MoveCarLeft,Right,UP,Down functions
       MoveCarLeft loads the CarLeft.png and moves one step (58 pixel which is the city width) to the left
       the same goes for right, up and down functons
       
                after moving one step we check again if we reached the number of dice, if not, move again.
    
       */
    public ImageIcon loadImageOfDice(int dice)
    {
        ImageIcon i;
        switch(dice){
            case 1: 
                return new javax.swing.ImageIcon(getClass().getResource("/drawables/1.png"));
            case 2:
                return new javax.swing.ImageIcon(getClass().getResource("/drawables/2.png"));
            case 3:
                return new javax.swing.ImageIcon(getClass().getResource("/drawables/3.png"));
            case 4:
                return new javax.swing.ImageIcon(getClass().getResource("/drawables/4.png"));
            case 5:
                return new javax.swing.ImageIcon(getClass().getResource("/drawables/5.png"));
            case 6:
                return new javax.swing.ImageIcon(getClass().getResource("/drawables/6.png"));
            default :
                System.out.println("SOMETHING IS WRONG IN THE loadImageOfDice");
        }
        
        return new ImageIcon();
                    
    }
    
       public void MoveCar(int dice)
       {
           int cx = jLabel2.getX();
           int cy = jLabel2.getY();
           for(int i=0; i<dice; i++)
           {
               jTextField3.setText(cx + "   " + cy);
               if(Constants.CurPos >= 0 && Constants.CurPos < 10)
                    MoveCarLeft();
               
                if(Constants.CurPos >= 10 && Constants.CurPos < 20)
                   MoveCarUP();
               
                 if(Constants.CurPos >= 20 && Constants.CurPos < 30)
                   MoveCarRight();
               
                 if(Constants.CurPos >= 30 && Constants.CurPos < 40)
                   MoveCarDown();
               
               Constants.CurPos++;
               if(Constants.CurPos == 40) Constants.CurPos = 0; //reaching 40 means you went back to GO
           }
       }
    
    public void MoveCarLeft()
    {
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/drawables/CarLeft.png")));
        jLabel2.setBounds(jLabel2.getX() - Constants.CityWidth, Constants.BoardHeight - Constants.HLine , Constants.CarDim, Constants.CarDim);       
        
    }
     public void MoveCarRight()
    {
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/drawables/CarRight.png")));
        jLabel2.setBounds(jLabel2.getX() + Constants.CityWidth, Constants.HLine/2, Constants.CarDim, Constants.CarDim);       
    }
     
      public void MoveCarUP()
    {
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/drawables/CarUP.png")));
        jLabel2.setBounds(Constants.VLine/2, jLabel2.getY() - Constants.CityWidth , Constants.CarDim, Constants.CarDim);       
    }
      
       public void MoveCarDown()
    {
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/drawables/CarDown.png")));
        jLabel2.setBounds(Constants.BoardWidth - Constants.VLine/2 , jLabel2.getY() + Constants.CarDim, Constants.CarDim, Constants.CarDim);       
    }
    
       
    

   
      
      
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BoardPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
